logging:
  level:
    root: INFO
    org.flyants.authorize: DEBUG
    org.springframework.web: TRACE
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/.h2/flyants-chat
    username: sa
    password: sa
    type: com.zaxxer.hikari.HikariDataSource
    platform: h2
  h2:
    console:
      settings:
        web-allow-others: true # 进行该配置后，h2 web consloe就可以在远程访问了。否则只能在本机访问。
      path: /h2 #进行该配置，你就可以通过YOUR_URL/h2访问h2 web consloe。YOUR_URL是你程序的访问URl。
      enabled: true #进行该配置，程序开启时就会启动h2 web consloe。当然这是默认的，如果你不想在启动程序时启动h2 web consloe，那么就设置为false。